Check requested tests are specified in config (#6)

diff --git a/.github/workflows/run_tests.yaml b/.github/workflows/run_tests.yaml
--- a/.github/workflows/run_tests.yaml
+++ b/.github/workflows/run_tests.yaml
@@ -29,3 +29,15 @@ jobs:
             echo "Test for workflow bad_workflow succeeded which should not have passed."
             exit 1
           fi
+          if python watt.py -e cromwell-84.jar -w not_a_workflow; then
+            echo "Test specifying non existent workflow not_a_workflow succeeded which should have raised exception."
+            exit 1
+          fi
+          if python watt.py -e cromwell-84.jar -t not_a_test; then
+            echo "Test specifying non existent test not_a_tes succeeded which should have raised exception."
+            exit 1
+          fi
+          if python watt.py -e cromwell-84.jar -w say_hello extract_stat -t expect_fail; then
+            echo "Test specifying non existent workflow/test combo say_hello:expect_fail succeeded which should have raised exception."
+            exit 1
+          fi
